name: CI for livechat Project
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  job_id:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: "actions/checkout@v3"

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIAL }}"

      - id: "compute-ssh"
        uses: "google-github-actions/ssh-compute@v0"
        with:
          instance_name: "${{ secrets.DEV_INSTANCE }}"
          user: "${{ secrets.GCP_USER }}"
          zone: "${{ secrets.GCP_REGION }}"
          ssh_private_key: "${{ secrets.GCP_PRIVATE_KEY_DEV }}"
          command: "sudo ./livechat-cdn.sh -b dev"
