name: CI for livechat Project
on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  job_id:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIAL }}'

    - id: 'compute-ssh'
      uses: 'google-github-actions/ssh-compute@v0'
      with:
        instance_name: '${{ secrets.STAGING_INSTANCE }}'
        user: '${{ secrets.GCP_USER }}'
        zone: '${{ secrets.GCP_REGION }}'
        ssh_private_key: '${{ secrets.GCP_PRIVATE_KEY_STAGING }}'
        command: 'sudo ./livechat-cdn.sh -b staging'
    - id: "get-error"
      run: |-
        echo '${{ steps.compute-ssh.outputs.stderr }}'
    - id: "get-stdout"
      run: |-
        echo '${{ steps.compute-ssh.outputs.stdout }}' | grep ready